### ISSUE TITLE
- [ ] Definir el título del proyecto

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_jag_ppi2020#1]

**Comment by BaleriaOspina** [comment]
<h1>Verb To-Be</h1>
<h2>hecho por: </h2>
    <h4>Baleria Ospina <br> Josselin Restrepo <br> Nataly Iriarte</h4>

**Comment by JohnFlorez25** [comment]
@BaleriaOspina El título cumple con lo acordado de acuerdo a lo que se va a realizar en el proyecto, confirmo que el título está en la wiki.
