### ISSUE TITLE
- [ ] Diseñar el diagrama de espina de pescado

### ISSUE THREAD

**Issue by JohnFlorez25** [JohnFlorez25/equipo1_jag_ppi2020#2]

**Comment by BaleriaOspina** [comment]
<h1>
        <strong> Declaración de la situación</strong>
    </h1>
    <p>En la institución educativa José Antonio Galán se evidencio la problemática de que muchos alumnos 
        <br> no saben el uso adecuado del verbo to-be. Esta dificultad puede ser causada debido a la metodología de aprendizaje que se brinda. 
        <br>Para mejorar la profundización y aclaración de este tema es muy útil el aplicativo “verb to-be” ya que se estaría implementando el conocimiento de una forma lúdica.
    </p>

**Comment by JohnFlorez25** [comment]
@BaleriaOspina @natalyiriarte @Marian-18 el Diagrama de espina de pescado debe estar asociado al problema identificado, en este no se coloca las descripciones o puntos a realizar en un aplicativo móvil.
